### ISSUE TITLE
A few small issues with tweaking the plugin

### ISSUE THREAD

**Issue by celtichawk** [ClockworkEJD/ares-eshtraits-plugin#1]
Figured I'd put this out there since I'm running into an issue with the plugin and don't know if it's something I did wrong, or plugin limits.

First off. I've got this on a game, and need to tweak it for my setting. That's involved changing the sheet_cmd to something more fitting. Which works fine. That's not where the issues are.

I changed the titles in the locale.yml file.

If I look at the sheet itself, it's fine. It has gear, vehicles, et al. But if I look at one of the parts of the sheet. it still shows as skills for instance instead of the changed name.

Second and more pressing bit. I'd like to get this working on the web portal with version .100. But, I'm not sure if the tweaking broke something. Mostly since i've got items in the fields with new titles. They show up fine on the client side.

But the web portal side is still the defaults however. I've followed the install instructions to the letter.

**Comment by forgottenmush** [comment]
I'm not sure exactly what was changed, but this is what I suspect might help.

The locale.yml file will change the display titles in the client, but does not affect the web portal.

The web portal custom code that is in the custom files folder will need to likewise be edited.

If you changed how the information is stored in the client, then the web files will have to be updated accordingly. If you're using the default fields and are just changing what the tab labels are, then you just need to change the labels in the chargen and profile custom tabs hbs files so that they display the new names.

Let me know if that helps.

**Comment by ClockworkEJD** [comment]
I'm not sure exactly what was changed, but this is what I suspect might help.

The locale.yml file will change the display titles in the client, but does not affect the web portal.

The web portal custom code that is in the custom files folder will need to likewise be edited.

If you changed how the information is stored in the client, then the web files will have to be updated accordingly. If you're using the default fields and are just changing what the tab labels are, then you just need to change the labels in the chargen and profile custom tabs hbs files so that they display the new names.

Let me know if that helps.

**Comment by ClockworkEJD** [comment]
Also if you go into flaws_cmd.rb you can see where it says "Flaws" there for the individual section. You can change the text there to make the individual sections use the different titles that you've chosen but you'll have to update each command: flaws_cmd, advantages_cmd, etc.

**Comment by celtichawk** [comment]
Thought the reply went through by email. but...
I've changed the attr name part in the _cmd.rb but that's not solving the web issues

I did

For the web stuff, I've done


<li><a data-toggle="tab" href="#eshtraits-powers">Gear</a></li>

in the custom tabs one, reloaded, redeployed the site and it still shows powers. All I did was, like I said, change the titles in locale.yml from Powers to Gear and logically, it should pick that up. The second issue is it's not reading what I've got in the list. if I have three things in a category, and click powers after clicking sheet, it just gives me nothing. I'm not sure if trying to work this around Fate is a part of causing the issues though.

**Comment by celtichawk** [comment]
To clarify.

I got the titles for the sections to work correctly on the client side. So that's not an issue. What is....is the web side of it. Which is the one that's stumping me. No matter what I change...it's still using the default names on the wiki, and won't pull up the listed traits when looking at the wiki.

As in....installed the plugin on my Fate game, change the titles in locales.yml and the section titles in the *_cmd.rb files.

That all works flawlessly on the client side. But I'm stuck on getting the web side of stuff to work however.

**Comment by ClockworkEJD** [comment]
Right, that's why I mentioned you needed to update the hbs files in the custom web portal files so that they have the right labels on them. The locale.yml file does not affect the portal at all.

https://github.com/celtichawk/ares-eshtraits-plugin/blob/master/custom_files/chargen-custom-tabs.hbs
https://github.com/celtichawk/ares-eshtraits-plugin/blob/master/custom_files/profile-custom-tabs.hbs

Those are the two files where the labels for the Tabs are located.

I'm not sure if working it around Fate is part of the problem since I'm not sure how or where Fate stores any of its information. If it uses the powers, skills, advantages, or flaws attributes on a character object, then it could be running into some problems. Other than that, the two shouldn't be having issues unless they're both trying to access the same attributes on a character object.

**Comment by celtichawk** [comment]
Okay that seems to work a little, but...still not picking up what's in the database set in the eshtraits plugin itself.

Fate's not the issue as far as I can tell. THe information's there for the plugin to grab, which it does. from a client.

I feel like the issue as well is I'm not sure what order I'm supposed to edit and load things since the Ares tutorial tells me to reload the site and profile data when I make a change, which resets it.

So what's the right order to do this, from editing the custom-tabs.hbs files, then is it reload the profile plugin or do I not touch that, or do I redeploy the website? I can edit the files fine. It's after that I get lost trying to follow the Ares instructions and make them work with the plugin and the wiki

**Comment by ClockworkEJD** [comment]
You shouldn't need to reload the profile plugin for the portal updates but you do need to redeploy the portal when you make changes to the custom portal files that I mentioned above. Feel free to toss me a friend request on Discord if you want and we can take a look at it together.

**Comment by celtichawk** [comment]
I've done that, and put all the files in. However, in the log when redeploying the site.

I get several killed messages when building, and a file already eexists error. The site deploys properly after that. But nothing displays when clicking a button however.

Is that down to the errors in the deployment with the killed errors and file already exists error?

**Comment by celtichawk** [comment]
I'm getting killed errors when redeploying however, and a file eexists error at the same time. It starts building, says killed and then goe through the rest of the process normally. I'm not sure if that's something I've done wrong. I'm using Ares v.100 and unsure if that's the main issue or not?

**Comment by ClockworkEJD** [comment]
I couldn't tell you. You might need Faraday's help with that. That's not something I've ever encountered.
